# Generated by Django 4.1 on 2022-12-21 10:31

from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todoitem",
            options={"ordering": ["due_date"]},
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="due_date",
            field=models.DateField(
                default=todo_app.models.on_week_hence, verbose_name="Due Date"
            ),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="title",
            field=models.CharField(max_length=100, unique=True, verbose_name="Title"),
        ),
    ]
