# Generated by Django 4.1 on 2022-12-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0002_alter_todoitem_options_alter_todoitem_due_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="title",
            field=models.CharField(max_length=100, unique=True, verbose_name="Title"),
        ),
    ]
